---
title: "Revolut-Improving KYC"
author: "Janki Shah"
date: "January 25, 2020"
output: html_document
---


```{r CWD, include=FALSE}
getwd() # check current working directory

```

```{r LoadLibraries, echo=FALSE, message=FALSE, results='hide', warning=FALSE}
library(readr)
library(dplyr)
library(tidyr)
library(Hmisc)
library(tidyverse)
library(ggplot2)
library(sqldf)
library(ggthemes)
library(stringr)
library(lubridate)
```


```{r DataLoad, echo=FALSE, message=FALSE, results='hide', warning=FALSE}
df_doc <- read_csv("doc_reports.csv")
View(df_doc)
df_facial <- read_csv("facial_similarity_reports.csv")
```


```{r DataCleaning, echo=FALSE, message=FALSE, results='hide', warning=FALSE}

#Check if both the file has same user_id and attempt_id 
# identical(df_doc$user_id, df_facial$user_id) #user_id
# identical(df_doc$attempt_id, df_facial$attempt_id)#attempt_id
# identical(df_doc$doc_created_at, df_facial$facial_created_at)#creted at


#Rename the columns
colnames(df_doc)<- c("Index_id","user_id","doc_result","doc_visual_authenticity_result",
                     "doc_image_integrity_result","doc_face_detection_result", 
                     "doc_image_quality_result","doc_created_at","doc_supported_document_result", 
                     "doc_conclusive_document_quality_result", "doc_colour_picture_result",  
                     "doc_data_validation_result", "doc_data_consistency_result", 
                     "doc_data_comparison_result", "doc_attempt_id","doc_police_record_result",
                     "doc_compromised_document_result", "doc_properties", "doc_sub_result")

colnames(df_facial)<- c("Index_id", "user_id","facial_result", "facial_comparison_result",
                        "facial_created_at","facial_facial_image_integrity_result",
                        "facial_visual_authenticity_result", "facial_properties","facial_attempt_id")


df_doc[is.na(df_doc)] = "unknown"
df_facial[is.na(df_facial)] = "unknown"

df_doc$doc_created_at <- as.POSIXct(df_doc$doc_created_at,format="%m/%d/%Y %H:%M:%S")
df_facial$facial_created_at <- as.POSIXct(df_facial$facial_created_at,format="%m/%d/%Y %H:%M:%S")

max_date_doc <- max(df_doc$doc_created_at)
#max_date_doc
min_date_doc <- min(df_doc$doc_created_at)
#min_date_doc

#Converting categorical Variables into factor 

df_doc$doc_result <- as.factor(df_doc$doc_result)
df_doc$doc_visual_authenticity_result <- as.factor(df_doc$doc_visual_authenticity_result)
df_doc$doc_image_integrity_result <- as.factor(df_doc$doc_image_integrity_result)
df_doc$doc_face_detection_result <- as.factor(df_doc$doc_face_detection_result)
df_doc$doc_image_quality_result <- as.factor(df_doc$doc_image_quality_result)
df_doc$doc_supported_document_result <- as.factor(df_doc$doc_supported_document_result)
df_doc$doc_conclusive_document_quality_result <- as.factor(df_doc$doc_conclusive_document_quality_result)
df_doc$doc_colour_picture_result <- as.factor(df_doc$doc_colour_picture_result)
df_doc$doc_data_validation_result <- as.factor(df_doc$doc_data_validation_result)
df_doc$doc_data_consistency_result <- as.factor(df_doc$doc_data_consistency_result)
df_doc$doc_data_comparison_result <- as.factor(df_doc$doc_data_comparison_result)
df_doc$doc_police_record_result <- as.factor(df_doc$doc_police_record_result)
df_doc$doc_compromised_document_result <- as.factor(df_doc$doc_compromised_document_result)
df_doc$doc_sub_result <-  as.factor(df_doc$doc_sub_result)

df_facial$facial_result <-as.factor(df_facial$facial_result)
df_facial$facial_comparison_result <-as.factor(df_facial$facial_comparison_result)
df_facial$facial_facial_image_integrity_result <-as.factor(df_facial$facial_facial_image_integrity_result)
df_facial$facial_visual_authenticity_result <-as.factor(df_facial$facial_visual_authenticity_result)


#Merge Two dataset
df_final <- merge(x = df_doc, y = df_facial, by = "Index_id")
df_final$user_id.y <- NULL
df_final$facial_created_at <- NULL
df_final$facial_attempt_id <- NULL
#levels(df_final$doc_result)
#levels(df_final$facial_result)

colnames(df_final)[colnames(df_final) == 'user_id.x'] <- 'user_id'
colnames(df_final)[colnames(df_final) == 'doc_created_at'] <- 'created_at'
colnames(df_final)[colnames(df_final) == 'doc_attempt_id'] <- 'attempt_id'

df_final$Pass <- ifelse(df_final$doc_result == "clear" & df_final$facial_result == "clear", "Yes", "No")

describe(df_final)#to check statistics

```


```{r PassFailRatio, echo=FALSE, warning=FALSE}

df_final_1 <- df_final %>% group_by(user_id) %>%
  tally()
df_final <- merge(df_final,df_final_1, by = 'user_id')
colnames(df_final)[colnames(df_final) == 'n'] <- 'no_of_attempts'

df_two_more_attempts <- df_final[(df_final$no_of_attempts >2),] #More than 2
length(unique(df_two_more_attempts$user_id))

df_final_onetwo <- df_final[(df_final$no_of_attempts <=2),] #<= 2
length(unique(df_final_onetwo$user_id))


df_two_attempts <- df_final[(df_final$no_of_attempts ==2),] # Twice
length(unique(df_two_attempts$user_id))

df_one_attempts <- df_final[(df_final$no_of_attempts ==1),] #First attempt
length(unique(df_one_attempts$user_id))

# Check the Pass ratio

total_customers <- length(df_final_onetwo$user_id) # TOTAL CUSTOMERS Including more than 2 attempt
total_pass_fail <- df_final_onetwo %>% group_by(Pass) %>% tally()
total_pass <- as.numeric(sqldf('select n from total_pass_fail where Pass = "Yes"'))
pass_rate <- as.numeric((total_pass / total_customers) * 100)
pass_rate

# Check only 1 attempt users

total_pass_fail_one <- df_one_attempts %>% group_by(Pass) %>% tally()
total_pass_one <- as.numeric(sqldf('select n from total_pass_fail_one where Pass = "Yes"'))
pass_rate_one_attempt <- as.numeric((total_pass_one / total_customers) * 100)
pass_rate_one_attempt

```

##### Chart aethletics declaration
```{r removemychartJunk, echo=FALSE, warning=FALSE}
myChartAttr <-  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "gray"), 
        axis.ticks.x=element_blank(), 
        axis.ticks.y=element_blank()) 

```



```{r KYCOverTimePeriod}
# Number of KYC over the period

df_date <- separate(data = df_final, col = created_at, into  = c('Date', 'Time'), sep = ' ')
df_date <- subset(df_date, select = c('user_id', 'Date', 'Time'))
df_date$month <- month(df_date$Date)

df_date$month_of_year <- month(df_date$Date)
df_date$month <- month(df_date$Date)
df_month <- df_date %>% 
  group_by(month) %>%
  tally()
colnames(df_month) <- c('month', 'freq')


ggplot(df_month, aes(month, freq, group=1)) +
  geom_line(color = "#008080", size=1.5) + 
  geom_point(color = "#008080", size=3) +  
  labs(x = "Month", y ="Number of KYC") + 
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "gray")) +
  scale_y_continuous(breaks = c(0, 10000, 20000, 30000, 40000, 50000)) 

```


```{r PassRateOverall}

df_one_attempts <- subset(df_one_attempts, subset = df_one_attempts$Pass == 'Yes')
df_one_attempts <- separate(data = df_one_attempts, col = created_at, into  = c('Date', 'Time'), sep = ' ')
df_one <- subset(df_one_attempts, select = c('user_id', 'Date', 'Time'))
df_one$month_of_year <- month(df_one$Date)
df_month_one <- df_one %>% 
  group_by(month_of_year) %>%
  tally()
colnames(df_month_one) <- c('month', 'freq')
ggplot(df_month_one, aes(month, freq, group=1)) +
  geom_line(color = "#008080", size=1.5) + 
  geom_point(color = "#008080", size=3) +  
  labs(x = "Month", y ="Number of KYC") + 
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "gray")) +
  scale_y_continuous(breaks = c(0, 5000, 10000, 15000, 20000, 25000)) 

df_final_onetwo_pass <- subset(df_final_onetwo, subset = df_final_onetwo$Pass == 'Yes')
df_final_onetwo_pass <- separate(data = df_final_onetwo_pass, col = created_at, into  = c('Date', 'Time'), sep = ' ')
df_two <- subset(df_final_onetwo_pass, select = c('user_id', 'Date', 'Time'))
df_two$month <- month(df_two$Date)
df_month_two <- df_two %>% 
  group_by(month) %>%
  tally()
colnames(df_month_two) <- c('month', 'freq')

df_month_passrate <- merge(df_month_two, df_month, by = 'month')
colnames(df_month_passrate) <- c('month', 'pass', 'total')
df_month_passrate$passrate <- (df_month_passrate$pass / df_month_passrate$total)*100

ggplot(df_month_passrate, aes(month, passrate, group=1)) +
  geom_line(color = "#008080", size=1.5) + 
  geom_point(color = "#008080", size=3) +  
  labs(x = "Month", y ="Pass rate (%)") + 
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "gray"))  +
  scale_y_continuous(breaks = c(60, 70, 80, 90, 100)) 



```


```{r fig.width=10, fig.height=2, warning=FALSE}
df_doc_facial_result <- subset(df_final_onetwo, select = c("user_id","doc_result","facial_result"))
colnames(df_doc_facial_result) <- c("user_id","Document", "Facial similarity")
df_doc_facial_result<- gather(df_doc_facial_result, check, result, Document:`Facial similarity`)
df_doc_facial_result <- df_doc_facial_result %>%  filter(!str_detect(result, 'unknown'))

ggplot(df_doc_facial_result, aes(check, ..count..)) + geom_bar(aes(fill = result), width = 0.65,position = "stack") + myChartAttr +scale_fill_manual(".", values = c("clear" = "#009a9a", "consider" = "#808080")) + scale_y_continuous(breaks = c(0, 30000, 60000, 90000, 120000, 150000))  + xlab("")+ ylab("") + coord_flip()


```

```{r doc_facial_check, fig.height= 7, fig.width=9, warning= FALSE}
df_doc_properties <- subset(df_final_onetwo, select = c("doc_visual_authenticity_result",
                    "doc_image_integrity_result","doc_face_detection_result",
                    "doc_image_quality_result", "doc_colour_picture_result", "doc_supported_document_result",
                     "doc_conclusive_document_quality_result",
                     "doc_data_validation_result", "doc_data_consistency_result",
                     "doc_data_comparison_result", "doc_police_record_result",
                     "doc_compromised_document_result"))
colnames(df_doc_properties) <- c("Visual authenticity", "Image integrity", "Face detection", "Image quality",
                            "Color quality", "Supported doc", "Conclusive doc",
                     "Data Validation", "Data consistency",
                     "Data comparison", "Police record",
                     "Compromised document")
df_doc_properties<- gather(df_doc_properties, check, result, `Visual authenticity`:`Compromised document`)
#levels(as.factor(df_doc_properties$result))
df_doc_properties[df_doc_properties == "unidentified"] = "unknown"

df_cause_doc <- subset(df_doc_properties, subset = result == "consider")
#levels(as.factor(df_cause_doc$check))

ggplot(df_doc_properties, aes(check, ..count..)) + geom_bar(aes(fill = result), width = 0.65,position = "stack") + myChartAttr + scale_fill_manual("", values = c("clear" = "#009a9a", "consider"="#808080", "unknown"="#b1b1b1")) + scale_y_continuous(breaks = c(0, 30000, 60000, 90000, 120000, 150000)) + xlab("")+ ylab("") +
theme(axis.text.x = element_text(angle = 45, hjust = 1)) + theme(legend.position = "none") 

ggplot(df_cause_doc,aes(x=check)) + geom_bar(width = 0.65) + myChartAttr +  
  scale_y_continuous(breaks = c(0, 10000, 20000, 30000, 40000)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+ xlab("")+ ylab("")

```

```{r FacialResult, fig.height= 4.5, fig.width=3.75}
df_facial_properties <- subset(df_final_onetwo, select = c("facial_comparison_result",
                        "facial_facial_image_integrity_result",
                        "facial_visual_authenticity_result"))
colnames(df_facial_properties) <- c("Comparison result", "Image integrity", "Visual authenticity")
df_facial_properties<- gather(df_facial_properties, check, result, `Comparison result`:`Visual authenticity`)
df_facial_properties[df_facial_properties == "unidentified"] = "unknown"

ggplot(df_facial_properties, aes(check, ..count..)) + geom_bar(aes(fill = result), width = 0.65, position = "stack") + myChartAttr + scale_fill_manual("", values = c("clear" = "#009a9a", "consider"="#808080", "unknown"="#b1b1b1")) + scale_y_continuous(breaks = c(0, 30000, 60000, 90000, 120000, 150000)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+ xlab("")+ ylab("")

```



```{r sub_result_check, fig.width=9, fig.height=2.5}

df_sub_result <- subset (df_final_onetwo, subset = doc_sub_result == "caution" | doc_sub_result == "suspected" | doc_sub_result == "rejected" , select = c("doc_sub_result", "created_at")) 
colnames(df_sub_result) <- c("subresult", "created_at") 
#levels(as.factor(df_sub_result$subresult))
cpalette = c("#808080","#808080","#808080")
df_sub_result$subresult <- as.factor(df_sub_result$subresult)
ggplot(df_sub_result,aes(x=subresult)) + geom_bar(fill=cpalette, width = 0.6) + myChartAttr +   xlab("")+ ylab("") +coord_flip()

df_sub_result <- separate(data = df_sub_result, col = created_at, into  = c('Date', 'Time'), sep = ' ')
df_sub_result_month <- subset(df_sub_result, select = c('subresult', 'Date'))
df_sub_result_month$Date <- as.Date(df_sub_result_month$Date)
df_sub_result_month$month <- month(df_sub_result_month$Date)
df_sub_result_month <- df_sub_result_month %>% 
  group_by(month,subresult) %>%
  tally()

```


